[HTM]
PERMANENCE_THRESHOLD      = 0.2

CONNECTION_PERMANENCE_INC = 0.03
CONNECTION_PERMANENCE_DEC = 0.01

COLUMN_COUNT              = 2048
COLUMN_CELL_COUNT         = 5
COLUMN_CONNECTION_DENSITY = 0.5
COLUMN_ACTIVATION_DENSITY = 0.02

DATA_WIDTH                = 16384
DATA_SAMPLE_COUNT         = 100
DATA_SPARSITY             = 0.2
